import './globals.css';

export const metadata = {
    title: 'Bayuguai',
    description: 'Generated by Bayuguai'
};

const className = '';

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={className}>{children}</body>
        </html>
    );
}
